.\"     Title: newgrp
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/23/2008
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "newgrp" "1" "11/23/2008" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
newgrp \- выполняет регистрацию пользователя в новой группе
.SH "СИНТАКСИС"
.HP 7
\fBnewgrp\fR [\-] [\fIгруппа\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBnewgrp\fR
используется для изменения ID текущей группы в работающем сеансе\&. Если указан необязательный параметр
\fB\-\fR, то рабочая среда пользователя будет реиницилизирована, как если бы пользователь заново вошёл в систему, иначе имеющаяся среда, включая текущий рабочий каталог, изменены не будут\&.
.PP
Программа
\fBnewgrp\fR
изменяет идентификатор текущей реальной группы на заданный или на группу по умолчанию, указанную в файле
\fI/etc/passwd\fR, в случае если имя группы не указано\&. Программа
\fBnewgrp\fR
также пытается добавить группу в список групп пользователя\&. Если пользователь не является суперпользователем, то его попросят ввести пароль, даже если он его не имеет (в файле
\fI/etc/shadow\fR, если для этого пользователя имеется запись в файле теневых паролей, иначе используется файл
\fI/etc/passwd\fR), а группа имеет, или если пользователь не является членом группы, а группа имеет пароль\&. Если пользователь не является членом группы, а у группы пустой пароль, то пользователю будет отказано в доступе\&.
.PP
Если есть запись для этой группы в файле
\fI/etc/gshadow\fR,то список членов и пароль этой группы будут взяты из этого файла, иначе используется запись из файла
\fI/etc/group\fR\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
\fI/etc/login\&.defs\fR
change the behavior of this tool:
.PP
\fBSYSLOG_SG_ENAB\fR (boolean)
.RS 4
Enable "syslog" logging of
\fBsg\fR
activity\&.
.RE
.SH "ФАЙЛЫ"
.PP
\fI/etc/passwd\fR
.RS 4
содержит информацию о пользователях
.RE
.PP
\fI/etc/shadow\fR
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
\fI/etc/group\fR
.RS 4
содержит информацию о группах
.RE
.PP
\fI/etc/gshadow\fR
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP

\fBid\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBsg\fR(1),
\fBgpasswd\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)\&.
