.\"     Title: passwd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/23/2008
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"
.TH "passwd" "1" "11/23/2008" "Пользовательские команды" "Пользовательские команды"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
passwd \- изменяет пароль пользователя
.SH "СИНТАКСИС"
.HP 7
\fBpasswd\fR [\fIпараметры\fR] [\fILOGIN\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBpasswd\fR
изменяет пароли пользовательских учётных записей\&. Обычный пользователь может изменить пароль только своей учётной записи, суперпользователь может изменить пароль любой учётной записи\&. Программа
\fBpasswd\fR
также изменяет информацию об учётной записи: полное имя пользователя, регистрационную оболочку командной строки или дату устаревания пароля и интервал\&.
.SS "Изменение пароля"
.PP
Сначала пользователя попросят ввести старый пароль, если он был\&. Этот пароль зашифровывается и сравнивается с имеющимся\&. У пользователя есть только одна попытка ввести правильный пароль\&. Для суперпользователя этот шаг пропускается, для того чтобы можно было изменить забытый пароль\&.
.PP
После ввода пароля проверяется информация об устаревании пароля, чтобы убедиться, что пользователю разрешено изменять пароль в настоящий момент\&. Если нет, то
\fBpasswd\fR
не производит изменение пароля и завершает работу\&.
.PP
Затем пользователю предложат дважды ввести новый пароль\&. Значение второго ввода сравнивается с первым и для изменения пароли из обеих попыток должны совпасть\&.
.PP
Затем пароль тестируется на сложность подбора\&. Согласно общим принципам, пароли должны быть длиной от 6 до 8 символов и включать один или более символов каждого типа:
.sp
.RS 4
\h'-04'\(bu\h'+03'строчные буквы
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'цифры от 0 до 9
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'знаки пунктуации
.RE
.PP
Не включайте системные символы стирания и удаления\&. Программа
\fBpasswd\fR
не примет пароль, который не имеет достаточной сложности\&.
.SS "Выбор пароля"
.PP
Безопасность пароля зависит от стойкости алгоритма шифрования и размера пространства ключа\&. В
\fIUNIX\fR
системах метод шифрования основан на алгоритме NBS DES и очень безопасен\&. Размер пространства ключа зависит от степени произвольности выбранного пароля\&.
.PP
Компромиссом в безопасности пароля является небрежный выбор пароля и сложность работы с ним\&. По этой причине, вы не должны использовать пароль, который является словом из словаря или который придётся записать из\-за его сложности\&. Также, пароль не должен быть названием чего\-либо, номером вашей лицензии, днём рождения и домашним адресом\&. Обо всём этом легко догадаться, что приведёт к нарушению безопасности системы\&.
.PP
You can find advices on how to choose a strong password on http://en\&.wikipedia\&.org/wiki/Password_strength
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBpasswd\fR:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Этот параметр можно использовать только вместе с
\fB\-S\fR
для вывода статуса всех пользователей\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR
.RS 4
Удалить пароль пользователя (сделать его пустым)\&. Это быстрый способ заблокировать пароль учётной записи\&. Это делает указанную учётную запись беспарольной\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expire\fR
.RS 4
Немедленно сделать пароль устаревшим\&. В результате это заставит пользователя изменить пароль при следующем входе в систему\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-i\fR, \fB\-\-inactive\fR\fIДНЕЙ\fR
.RS 4
Этот параметр используется для блокировки учётной записи по прошествии заданного числа дней после устаревания пароля\&. То есть, если пароль устарел и прошло более указанных
\fIДНЕЙ\fR, то пользователь больше не сможет использовать данную учётную запись\&.
.RE
.PP
\fB\-k\fR, \fB\-\-keep\-tokens\fR
.RS 4
Указывает, что изменение пароля нужно выполнить только для устаревших ключей аутентификации (паролей)\&. Пользователи хотят оставить свои непросроченные ключи нетронутыми\&.
.RE
.PP
\fB\-l\fR, \fB\-\-lock\fR
.RS 4
Lock the named account\&. This option disables an account by changing the password to a value which matches no possible encrypted value, and by setting the account expiry field to 1\&.
.RE
.PP
\fB\-m\fR, \fB\-\-mindays\fR\fIМИН_ДНЕЙ\fR
.RS 4
Задать
\fIминимальное количество дней\fR
между сменой пароля\&. Нулевое значение этого поля указывает на то, что пользователь может менять свой пароль когда захочет\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Не выводить сообщений при работе\&.
.RE
.PP
\fB\-r\fR, \fB\-\-repository\fR\fIРЕПОЗИТОРИЙ\fR
.RS 4
Изменить пароль в
\fIРЕПОЗИТОРИИ\fR\&.
.RE
.PP
\fB\-S\fR, \fB\-\-status\fR
.RS 4
Показать состояние учётной записи\&. Информация о состоянии содержит 7 полей\&. Первое поле содержит имя учётной записи\&. Второе поле указывает, заблокирована ли учётная запись (L), она без пароля (NP) или у неё есть рабочий пароль (P)\&. Третье поле хранит дату последнего изменения пароля\&. В следующих четырёх полях хранятся минимальный срок, максимальный срок, период выдачи предупреждения и период неактивности пароля\&. Эти сроки измеряются в днях\&.
.RE
.PP
\fB\-u\fR, \fB\-\-unlock\fR
.RS 4
Unlock the named account\&. This option re\-enables an account by changing the password back to its previous value (to value before using
\fB\-l\fR
option), and by resetting the account expiry field\&.
.RE
.PP
\fB\-w\fR, \fB\-\-warndays\fR\fIПРЕД_ДНЕЙ\fR
.RS 4
Установить число дней выдачи предупреждения, перед тем как потребуется смена пароля\&. В параметре
\fIПРЕД_ДНЕЙ\fR
указывается число дней перед тем как пароль устареет, в течении которых пользователю будут напоминать, что пароль скоро устареет\&.
.RE
.PP
\fB\-x\fR, \fB\-\-maxdays\fR\fIМАКС_ДНЕЙ\fR
.RS 4
Установить максимальное количество дней, в течении которых пароль остаётся рабочим\&. После
\fIМАКС_ДНЕЙ\fR
пароль нужно изменить\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не все параметры могут работать\&. Сложность пароля проверяется по разному на разных машинах\&. Пользователю настоятельно советуется выбирать пароль такой сложности, чтобы ему нормально работалось\&. Пользователи не могут изменять свои пароли в системе, если включён NIS и они не вошли на сервер NIS\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
\fI/etc/login\&.defs\fR
change the behavior of this tool:
.PP
\fBENCRYPT_METHOD\fR (string)
.RS 4
This defines the system default encryption algorithm for encrypting passwords (if no algorithm are specified on the command line)\&.
.sp
It can take one of these values:
.sp
.RS 4
\h'-04'\(bu\h'+03'\fIDES\fR
(default)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fIMD5\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fISHA256\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fISHA512\fR
.RE
.IP "" 4
.sp
Note: this parameter overrides the
\fBMD5_CRYPT_ENAB\fR
variable\&.
.sp
Note: if you use PAM, it is recommended to set this variable consistently with the PAM modules configuration\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (boolean)
.RS 4
Indicate if passwords must be encrypted using the MD5\-based algorithm\&. If set to
\fIyes\fR, new passwords will be encrypted using the MD5\-based algorithm compatible with the one used by recent releases of FreeBSD\&. It supports passwords of unlimited length and longer salt strings\&. Set to
\fIno\fR
if you need to copy encrypted passwords to other systems which don\'t understand the new algorithm\&. Default is
\fIno\fR\&.
.sp
This variable is superceded by the
\fBENCRYPT_METHOD\fR
variable or by any command line option used to configure the encryption algorithm\&.
.sp
This variable is deprecated\&. You should use
\fBENCRYPT_METHOD\fR\&.
.sp
Note: if you use PAM, it is recommended to set this variable consistently with the PAM modules configuration\&.
.RE
.PP
\fBOBSCURE_CHECKS_ENAB\fR (boolean)
.RS 4
Enable additional checks upon password changes\&.
.RE
.PP
\fBPASS_ALWAYS_WARN\fR (boolean)
.RS 4
Warn about weak passwords (but still allow them) if you are root\&.
.RE
.PP
\fBPASS_CHANGE_TRIES\fR (number)
.RS 4
Maximum number of attempts to change password if rejected (too easy)\&.
.RE
.PP
\fBPASS_MAX_LEN\fR (number), \fBPASS_MIN_LEN\fR (number)
.RS 4
Number of significant characters in the password for crypt()\&.
\fBPASS_MAX_LEN\fR
is 8 by default\&. Don\'t change unless your crypt() is better\&. This is ignored if
\fBMD5_CRYPT_ENAB\fR
set to
\fIyes\fR\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (number), \fBSHA_CRYPT_MAX_ROUNDS\fR (number)
.RS 4
When
\fBENCRYPT_METHOD\fR
is set to
\fISHA256\fR
or
\fISHA512\fR, this defines the number of SHA rounds used by the encryption algorithm by default (when the number of rounds is not specified on the command line)\&.
.sp
With a lot of rounds, it is more difficult to brute forcing the password\&. But note also that more CPU resources will be needed to authenticate users\&.
.sp
If not specified, the libc will choose the default number of rounds (5000)\&.
.sp
The values must be inside the 1000\-999999999 range\&.
.sp
If only one of the
\fBSHA_CRYPT_MIN_ROUNDS\fR
or
\fBSHA_CRYPT_MAX_ROUNDS\fR
values is set, then this value will be used\&.
.sp
If
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, the highest value will be used\&.
.RE
.SH "ФАЙЛЫ"
.PP
\fI/etc/passwd\fR
.RS 4
содержит информацию о пользователях
.RE
.PP
\fI/etc/shadow\fR
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBpasswd\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
доступ запрещён
.RE
.PP
\fI2\fR
.RS 4
недопустимая комбинация параметров
.RE
.PP
\fI3\fR
.RS 4
неожиданная ошибка при работе, ничего не сделано
.RE
.PP
\fI4\fR
.RS 4
неожиданная ошибка при работе, отсутствует файл
\fIpasswd\fR
.RE
.PP
\fI5\fR
.RS 4
файл
\fIpasswd\fR
занят другой программой, попробуйте ещё раз
.RE
.PP
\fI6\fR
.RS 4
недопустимое значение параметра
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
