.\"     Title: shadow
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/23/2008
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"
.TH "shadow" "5" "11/23/2008" "Форматы файлов" "Форматы файлов"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "НАЗВАНИЕ"
shadow \- файл с защищаемой информацией о пользователях
.SH "ОПИСАНИЕ"
.PP
\fIshadow\fR
содержит шифрованные пароли учётных записей пользователей и необязательную информацию об устаревании пароля\&. Включает в себя:
.sp
.RS 4
\h'-04'\(bu\h'+03'имя пользователя для входа в систему
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'шифрованный пароль
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'число дней с момента последнего изменения пароля, начиная с 1 января 1970 года
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'число дней, перед тем как пароль может быть изменён
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'число дней, после которых пароль должен быть изменён
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'число дней, за сколько пользователя начнут предупреждать, что пароль устаревает
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'число дней, после устаревания пароля для блокировки учётной записи
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'дней, отсчитывая с 1 января 1970 года, когда учётная запись была заблокирована
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'зарезервированное поле
.RE
.PP
The password field must be filled\&. The encrypted password consists of 13 to 24 characters from the 64 character alphabet a thru z, A thru Z, 0 thru 9, \e\&. and /\&. Optionally it can start with a "$" character\&. This means the encrypted password was generated using another (not DES) algorithm\&. For example if it starts with "$1$" it means the MD5\-based algorithm was used\&.
.PP
Подробней о пароле смотрите на странице руководства
\fBcrypt\fR(3)\&.
.PP
Если поле пароля содержит строку, которая не удовлетворяет требованиям
\fBcrypt\fR(3), например содержит ! или *, то пользователь не сможет использовать этот unix пароль для регистрации с учётом настроек
\fBpam\fR(7)\&.
.PP
Дата последнего изменения пароля задаётся в днях, прошедших с 1 января 1970 года\&. Пароль не может быть изменён пока не пройдёт положенное число дней, и должен быть изменён после максимального числа дней\&. Если обязательное минимальное число дней больше чем максимальное число дней, то такой пароль не может быть изменён пользователем\&.
.PP
Учётная запись считается неактивной и будет заблокирована, если пароль не был изменён за заданное число дней после устаревания пароля\&. Учётная запись также будет заблокирована в заданный день, независимо от другой информации об устаревании пароля\&.
.PP
Информация из этого файла заменяет любой пароль или информацию об устаревании, содержащуюся в файле
\fI/etc/passwd\fR\&.
.PP
Этот файл должен быть недоступен обычному пользователю, если нужно обеспечить безопасность паролей\&.
.SH "ФАЙЛЫ"
.PP
\fI/etc/passwd\fR
.RS 4
содержит информацию о пользователях
.RE
.PP
\fI/etc/shadow\fR
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchage\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBpasswd\fR(1),
\fBpasswd\fR(5),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsulogin\fR(8)\&.
