.\"     Title: pwck
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 23-11-2008
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"
.TH "PWCK" "8" "23-11-2008" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAMN"
pwck \- validera integriteten för lösenordsfiler
.SH "SYNOPSIS"
.HP 5
\fBpwck\fR [\-q] [\-s] [\fIpasswd\fR\ [\ \fIshadow\fR\ ]]
.HP 5
\fBpwck\fR [\-q] [\-r] [\fIpasswd\fR\ \fIshadow\fR]
.SH "BESKRIVNING"
.PP
The
\fBpwck\fR
command verifies the integrity of the system authentication information\&. All entries in the
\fI/etc/passwd\fR
and
\fI/etc/shadow\fR
are checked to see that the entry has the proper format and valid data in each field\&. The user is prompted to delete entries that are improperly formatted or which have other uncorrectable errors\&.
.PP
Kontroller görs för att validera att varje post har:
.sp
.RS 4
\h'-04'\(bu\h'+03'korrekt antal fält
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ett unikt användarnamn
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'en giltig identifierare för användare och grupp
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'en giltig primär grupp
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'en giltig hemkatalog
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'ett giltigt inloggningsskal
.RE
.PP
The checks for correct number of fields and unique user name are fatal\&. If the entry has the wrong number of fields, the user will be prompted to delete the entire line\&. If the user does not answer affirmatively, all further checks are bypassed\&. An entry with a duplicated user name is prompted for deletion, but the remaining checks will still be made\&. All other errors are warning and the user is encouraged to run the
\fBusermod\fR
command to correct the error\&.
.PP
The commands which operate on the
\fI/etc/passwd\fR
file are not able to alter corrupted or duplicated entries\&.
\fBpwck\fR
should be used in those circumstances to remove the offending entry\&.
.SH "FLAGGOR"
.PP
Flaggorna som gäller för kommandot
\fBpwck\fR
är:
.PP
\fB\-q\fR
.RS 4
Report errors only\&. The warnings which do not require any action from the user won\'t be displayed\&.
.RE
.PP
\fB\-r\fR
.RS 4
Starta kommandot
\fBpwck\fR
i skrivskyddat läge\&.
.RE
.PP
\fB\-s\fR
.RS 4
Sorterar poster i
\fI/etc/passwd\fR
och
\fI/etc/shadow\fR
efter UID\&.
.RE
.PP
By default,
\fBpwck\fR
operates on the files
\fI/etc/passwd\fR
and
\fI/etc/shadow\fR\&. The user may select alternate files with the
\fIpasswd\fR
and
\fIshadow\fR
parameters\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
\fI/etc/login\&.defs\fR
change the behavior of this tool:
.PP
\fBPASS_MAX_DAYS\fR (number)
.RS 4
The maximum number of days a password may be used\&. If the password is older than this, a password change will be forced\&. If not specified, \-1 will be assumed (which disables the restriction)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (number)
.RS 4
The minimum number of days allowed between password changes\&. Any password changes attempted sooner than this will be rejected\&. If not specified, \-1 will be assumed (which disables the restriction)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (number)
.RS 4
The number of days warning given before a password expires\&. A zero means warning is given only upon the day of expiration, a negative value means no warning is given\&. If not specified, no warning will be provided\&.
.RE
.SH "FILER"
.PP
\fI/etc/group\fR
.RS 4
Gruppkontoinformation\&.
.RE
.PP
\fI/etc/passwd\fR
.RS 4
Användarkontoinformation\&.
.RE
.PP
\fI/etc/shadow\fR
.RS 4
Säker användarkontoinformation\&.
.RE
.SH "SE OCKSÅ"
.PP
\fBgroup\fR(5),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8)\&.
.SH "AVSLUTNINGSVÄRDEN"
.PP
Kommandot
\fBpwck\fR
avslutas med följande värden:
.PP
\fI0\fR
.RS 4
lyckad
.RE
.PP
\fI1\fR
.RS 4
ogiltig kommandosyntax
.RE
.PP
\fI2\fR
.RS 4
en eller flera felaktiga lösenordsposter
.RE
.PP
\fI3\fR
.RS 4
kan inte öppna lösenordsfiler
.RE
.PP
\fI4\fR
.RS 4
kan inte låsa lösenordsfiler
.RE
.PP
\fI5\fR
.RS 4
kan inte uppdatera lösenordsfiler
.RE
