.\"     Title: chfn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 23/11/2008
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "CHFN" "1" "23/11/2008" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
chfn \- Modifier le nom complet et les informations associées à un utilisateur
.SH "SYNOPSIS"
.HP 5
\fBchfn\fR [\-f\ \fInom_complet\fR] [\-r\ \fIno_bureau\fR] [\-w\ \fItel_bureau\fR] [\-h\ \fItel_perso\fR] [\-o\ \fIautre\fR] [\fIutilisateur\fR]
.SH "DESCRIPTION"
.PP
The
\fBchfn\fR
command changes user fullname, office number, office extension, and home phone number information for a user\'s account\&. This information is typically printed by
\fBfinger\fR(1)
and similar programs\&. A normal user may only change the fields for her own account, subject to the restrictions in
\fI/etc/login\&.defs\fR\&. (The default configuration is to prevent users from changing their fullname\&.) The superuser may change any field for any account\&. Additionally, only the superuser may use the
\fB\-o\fR
option to change the undefined portions of the GECOS field\&.
.PP
These fields must not contain any colons\&. Except for the
\fIother\fR
field, they should not contain any comma or equal sign\&. It is also recommended to avoid non\-US\-ASCII characters, but this is only enforced for the phone numbers\&. The
\fIother\fR
field is used to store accounting information used by other applications\&.
.PP
Si aucune option n\'est sélectionnée,
\fBchfn\fR
opère de manière interactive, demandant à l\'utilisateur d\'entrer les valeurs actuelles de chacun des champs\&. Entrer une nouvelle valeur pour la modifier, ou de laisser une ligne blanche pour conserver la valeur actuelle\&. La valeur actuelle est indiquée entre crochets (\fB[ ]\fR)\&. En l\'absence d\'option,
\fBchfn\fR
opère sur l\'utilisateur actuel\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
\fI/etc/login\&.defs\fR
change the behavior of this tool:
.PP
\fBCHFN_AUTH\fR (boolean)
.RS 4
If
\fIyes\fR, the
\fBchfn\fR
program will require authentication before making any changes, unless run by the superuser\&.
.RE
.PP
\fBCHFN_RESTRICT\fR (string)
.RS 4
This parameter specifies which values in the
\fIgecos\fR
field of the
\fI/etc/passwd\fR
file may be changed by regular users using the
\fBchfn\fR
program\&. It can be any combination of letters
\fIf\fR,
\fIr\fR,
\fIw\fR,
\fIh\fR, for Full name, Room number, Work phone, and Home phone, respectively\&. For backward compatibility,
\fIyes\fR
is equivalent to
\fIrwh\fR
and
\fIno\fR
is equivalent to
\fIfrwh\fR\&. If not specified, only the superuser can make any changes\&. The most restrictive setting is better achieved by not installing
\fBchfn\fR
SUID\&.
.RE
.PP
\fBLOGIN_STRING\fR (string)
.RS 4
The string used for prompting a password\&. The default is to use "Password: ", or a translation of that string\&. If you set this variable, the prompt will no be translated\&.
.sp
If the string contains
\fI%s\fR, this will be replaced by the user\'s name\&.
.RE
.SH "FICHIERS"
.PP
\fI/etc/login\&.defs\fR
.RS 4
Configuration de la suite des mots de passe cachés \(Fo\ \&shadow password\ \&\(Fc\&.
.RE
.PP
\fI/etc/passwd\fR
.RS 4
Informations sur les comptes des utilisateurs\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBchsh\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5)\&.
