.\"     Title: groups
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 23/11/2008
.\"    Manual: Commandes utilisateur
.\"    Source: Commandes utilisateur
.\"
.TH "GROUPS" "1" "23/11/2008" "Commandes utilisateur" "Commandes utilisateur"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NOM"
groups \- Afficher la liste des groupes auxquels appartient l'utilisateur
.SH "SYNOPSIS"
.HP 7
\fBgroups\fR [\fIutilisateur\fR]
.SH "DESCRIPTION"
.PP
The
\fBgroups\fR
command displays the current group names or ID values\&. If the value does not have a corresponding entry in
\fI/etc/group\fR, the value will be displayed as the numerical group value\&. The optional
\fIuser\fR
parameter will display the groups for the named
\fIuser\fR\&.
.SH "NOTE"
.PP
Sur les systèmes qui ne gèrent pas l\'appartenance à plusieurs groupes, seules les informations contenues dans
\fI/etc/group\fR
sont affichées\&. L\'utilisateur doit utiliser
\fBnewgrp\fR
ou
\fBsg\fR
pour modifier l\'identifiant de groupe réel et effectif\&.
.SH "FICHIERS"
.PP
\fI/etc/group\fR
.RS 4
Informations sur les groupes\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2)\&.
