.\"     Title: chpasswd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/23/2008
.\"    Manual: System Management Commands
.\"    Source: System Management Commands
.\"
.TH "CHPASSWD" "8" "11/23/2008" "System Management Commands" "System Management Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
chpasswd \- update passwords in batch mode
.SH "SYNOPSIS"
.HP 9
\fBchpasswd\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
The
\fBchpasswd\fR
command reads a list of user name and password pairs from standard input and uses this information to update a group of existing users\&. Each line is of the format:
.PP

\fIuser_name\fR:\fIpassword\fR
.PP
By default the supplied password must be in clear\-text, and is encrypted by
\fBchpasswd\fR\&. Also the password age will be updated, if present\&.
.PP
The default encryption algorithm can be defined for the system with the ENCRYPT_METHOD variable of
\fI/etc/login\&.defs\fR, and can be overwiten with the
\fB\-e\fR,
\fB\-m\fR, or
\fB\-c\fR
options\&.
.PP
This command is intended to be used in a large system environment where many accounts are created at a single time\&.
.SH "OPTIONS"
.PP
The options which apply to the
\fBchpasswd\fR
command are:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Use the specified method to encrypt the passwords\&.
.sp
The available methods are DES, MD5, NONE, and SHA256 or SHA512 if your libc support these methods\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Supplied passwords are in encrypted form\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help message and exit\&.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
Use MD5 encryption instead of DES when the supplied passwords are not encrypted\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Use the specified number of rounds to encrypt the passwords\&.
.sp
The value 0 means that the system will choose the default number of rounds for the crypt method (5000)\&.
.sp
A minimal value of 1000 and a maximal value of 999,999,999 will be enforced\&.
.sp
You can only use this option with the SHA256 or SHA512 crypt method\&.
.sp
By default, the number of rounds is defined by the SHA_CRYPT_MIN_ROUNDS and SHA_CRYPT_MAX_ROUNDS variables in
\fI/etc/login\&.defs\fR\&.
.RE
.SH "CAVEATS"
.PP
Remember to set permissions or umask to prevent readability of unencrypted files by other users\&.
.PP
PAM is not used to update the passwords\&. Only
\fI/etc/passwd\fR
and
\fI/etc/shadow\fR
are updated, and the various checks or options provided by PAM modules are not used\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
\fI/etc/login\&.defs\fR
change the behavior of this tool:
.PP
\fBENCRYPT_METHOD\fR (string)
.RS 4
This defines the system default encryption algorithm for encrypting passwords (if no algorithm are specified on the command line)\&.
.sp
It can take one of these values:
.sp
.RS 4
\h'-04'\(bu\h'+03'\fIDES\fR
(default)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fIMD5\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fISHA256\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\fISHA512\fR
.RE
.IP "" 4
.sp
Note: this parameter overrides the
\fBMD5_CRYPT_ENAB\fR
variable\&.
.sp
Note: if you use PAM, it is recommended to set this variable consistently with the PAM modules configuration\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (boolean)
.RS 4
Indicate if passwords must be encrypted using the MD5\-based algorithm\&. If set to
\fIyes\fR, new passwords will be encrypted using the MD5\-based algorithm compatible with the one used by recent releases of FreeBSD\&. It supports passwords of unlimited length and longer salt strings\&. Set to
\fIno\fR
if you need to copy encrypted passwords to other systems which don\'t understand the new algorithm\&. Default is
\fIno\fR\&.
.sp
This variable is superceded by the
\fBENCRYPT_METHOD\fR
variable or by any command line option used to configure the encryption algorithm\&.
.sp
This variable is deprecated\&. You should use
\fBENCRYPT_METHOD\fR\&.
.sp
Note: if you use PAM, it is recommended to set this variable consistently with the PAM modules configuration\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (number), \fBSHA_CRYPT_MAX_ROUNDS\fR (number)
.RS 4
When
\fBENCRYPT_METHOD\fR
is set to
\fISHA256\fR
or
\fISHA512\fR, this defines the number of SHA rounds used by the encryption algorithm by default (when the number of rounds is not specified on the command line)\&.
.sp
With a lot of rounds, it is more difficult to brute forcing the password\&. But note also that more CPU resources will be needed to authenticate users\&.
.sp
If not specified, the libc will choose the default number of rounds (5000)\&.
.sp
The values must be inside the 1000\-999999999 range\&.
.sp
If only one of the
\fBSHA_CRYPT_MIN_ROUNDS\fR
or
\fBSHA_CRYPT_MAX_ROUNDS\fR
values is set, then this value will be used\&.
.sp
If
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, the highest value will be used\&.
.RE
.SH "FILES"
.PP
\fI/etc/passwd\fR
.RS 4
User account information\&.
.RE
.PP
\fI/etc/shadow\fR
.RS 4
Secure user account information\&.
.RE
.PP
\fI/etc/login\&.defs\fR
.RS 4
Shadow password suite configuration\&.
.RE
.SH "SEE ALSO"
.PP

\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBuseradd\fR(8),
\fBlogin.defs\fR(5)\&.
