eaccelerator.lo: /home/bart/development/eaccelerator/branches/0.9.5/eaccelerator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/eaccelerator.c -o eaccelerator.lo 
optimize.lo: /home/bart/development/eaccelerator/branches/0.9.5/optimize.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/optimize.c -o optimize.lo 
encoder.lo: /home/bart/development/eaccelerator/branches/0.9.5/encoder.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/encoder.c -o encoder.lo 
loader.lo: /home/bart/development/eaccelerator/branches/0.9.5/loader.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/loader.c -o loader.lo 
opcodes.lo: /home/bart/development/eaccelerator/branches/0.9.5/opcodes.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/opcodes.c -o opcodes.lo 
content.lo: /home/bart/development/eaccelerator/branches/0.9.5/content.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/content.c -o content.lo 
mm.lo: /home/bart/development/eaccelerator/branches/0.9.5/mm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/mm.c -o mm.lo 
session.lo: /home/bart/development/eaccelerator/branches/0.9.5/session.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/session.c -o session.lo 
shm.lo: /home/bart/development/eaccelerator/branches/0.9.5/shm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/shm.c -o shm.lo 
debug.lo: /home/bart/development/eaccelerator/branches/0.9.5/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/debug.c -o debug.lo 
cache.lo: /home/bart/development/eaccelerator/branches/0.9.5/cache.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/cache.c -o cache.lo 
ea_restore.lo: /home/bart/development/eaccelerator/branches/0.9.5/ea_restore.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/ea_restore.c -o ea_restore.lo 
ea_store.lo: /home/bart/development/eaccelerator/branches/0.9.5/ea_store.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/ea_store.c -o ea_store.lo 
ea_info.lo: /home/bart/development/eaccelerator/branches/0.9.5/ea_info.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/ea_info.c -o ea_info.lo 
ea_dasm.lo: /home/bart/development/eaccelerator/branches/0.9.5/ea_dasm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bart/development/eaccelerator/branches/0.9.5 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bart/development/eaccelerator/branches/0.9.5/ea_dasm.c -o ea_dasm.lo 
$(phplibdir)/eaccelerator.la: ./eaccelerator.la
	$(LIBTOOL) --mode=install cp ./eaccelerator.la $(phplibdir)

./eaccelerator.la: $(shared_objects_eaccelerator) $(EACCELERATOR_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_eaccelerator) $(EACCELERATOR_SHARED_LIBADD)

