#!/bin/sh
#
# mDNSResponder:       Starts the mDNSResponder Daemon
#
# $Id: S9mDNSResponder,v 1.2.2.3.2.3 2009/02/12 08:07:00 wiley Exp $
#
# description: This is a daemon which runs on Howl clients to perform \
#              Zeroconf service discovery on a network.  mDNSResponder must be running on systems \
#              that use Howl for service discovery. \
#              mDNSResponder should not be running otherwise.
# processname: mDNSResponder
# config: /etc/mDNSResponder.conf

start() {
  /bin/echo -n "==> Starting mDNSResponder ................................ "
  /usr/bin/mDNSResponder -f /etc/mDNSResponder.conf >/dev/null 2>&1
  if [ "$?" == 0 ]; then
    /bin/echo "[ OK ]"
  else
    /bin/echo "[FAIL]"
  fi
}

stop() {
  /bin/echo -n "==> Stopping mDNSResponder ................................ "
  /usr/bin/killall -q -3  mDNSResponder >/dev/null 2>&1
  if [ "$?" == 0 ]; then
    /bin/echo "[ OK ]"
  else
    /bin/echo "[FAIL]"
  fi
}

restart() {
  (sleep 5; stop; start) &
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  condrestart)
    [ -f /var/lock/subsys/mDNSResponder ] && restart || :
  ;;
  *)
    /bin/echo $"Usage: $0 {start|stop|restart|condrestart}"
    exit 1
esac

exit 0
